[global]
# general appearance
monitor = 0
follow = mouse
scale = 0

# geometry / placement
# Dunst v1.13 supports dynamic width/height and tuple offset syntax.
width  = (200, 400)
height = (50, 200)
origin = top-right
offset = (10, 48)

# window / spacing
frame_width        = 2
separator_height   = 2
separator_color    = frame
corner_radius      = 0
corners            = all
padding            = 15
horizontal_padding = 15
gap_size           = 5
line_height        = 10

# notification behavior
sort                 = update
notification_limit   = 3
indicate_hidden      = yes
stack_duplicates     = yes
hide_duplicate_count = yes
idle_threshold       = 120
show_age_threshold   = 20
show_indicators      = no
sticky_history       = yes
history_length       = 50
always_run_script    = true

# font & text
font = Hack Nerd Font Mono 12
markup = full
word_wrap = yes
ellipsize = end
format = "<b>%s</b>\n%b\n"
ignore_newline = no
alignment = left
vertical_alignment = center

# progress bars
progress_bar               = true
progress_bar_height        = 10
progress_bar_frame_width   = 1
progress_bar_min_width     = 150
progress_bar_max_width     = 300
progress_bar_corner_radius = 0
progress_bar_corners       = none

# icons
enable_recursive_icon_lookup = true
icon_position      = left
min_icon_size      = 24
max_icon_size      = 48
icon_theme         = "Adwaita"
icon_corner_radius = 0
icon_corners       = none
text_icon_padding  = 0

# actions / metadata
browser = /usr/bin/firefox -new-tab
title = Dunst
class = Dunst
mouse_left_click = close_current
mouse_middle_click = do_action, close_current
mouse_right_click = close_all

# keyboard shortcuts, X11 only
close     = ctrl+space
close_all = ctrl+shift+space
history   = ctrl+grave
context   = ctrl+shift+grave

[urgency_low]
background  = "#282738"
foreground  = "#ffd5cd"
frame_color = "#282738"
timeout = 3
# icon = ~/.ochaya/dunst/images/notification.png

[urgency_normal]
background  = "#282738"
foreground  = "#ffd5cd"
frame_color = "#282738"
timeout = 8
# icon = ~/.ochaya/dunst/images/notification.png

[urgency_critical]
background  = "#282738"
foreground  = "#ffd5cd"
frame_color = "#282738"
timeout = 0
# icon = ~/.config/dunst/images/notification.png
