[module/memory]
type = internal/memory
interval = 1

format = <label>
; format-padding = 1
format-prefix = %{T13}󰍛%{T-}
format-prefix-foreground = ${colors.blue}
format-prefix-padding-left = 2
format-prefix-padding-right = 1
label = %{T2}%percentage_used%%%{T-}
label-foreground = ${colors.fg}
label-padding-right = 1
